const wiki_menus = [
    {
        id: 'data-science',
        name: 'Data Science',
        title: 'IBM Data Science Professional Certificate',
        file: 'data/data-science.csv',
        link: '',
        updated: 'September 20th, 2020',
        width: '1500',
        height: '2200',
    },
    {
        id: 'advanced-data-science',
        name: 'Advanced Data Science',
        title: 'Advanced Data Science with IBM Specialization',
        file: 'data/advanced-data-science.csv',
        link: '',
        updated: 'September 21th, 2020',
        width: '1500',
        height: '2200',
    },
    {
        id: 'artificial-intelligence',
        name: 'Artificial Intelligence',
        title: 'Artificial Intelligence',
        file: 'data/ai.csv',
        link: '',
        updated: 'January 03nd, 2020',
        width: '1500',
        height: '2200',
    },
    {
        id: 'mathematics-for-machine-learning',
        name: 'Mathematics for Machine Learning',
        title: 'Mathematics for Machine Learning',
        file: 'data/mathematics-for-machine-learning.csv',
        link: '',
        updated: 'December 05th, 2020',
        width: '1500',
        height: '2200',
    },
]